name = "io_stream"
version = "1.0.0"

description = "IO streams for gleam with support for files and stdio."
licences = ["MIT"]
repository = { type = "github", user = "amin-not-found", repo = "gleam_io_stream" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
