name = "io_streams"
version = "1.0.0"

description = "IO streams for gleam with support for files and stdio."
licences = ["MIT"]
#repository = { type = "github", user = "", repo = "" }

[dependencies]
gleam_stdlib = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
